spring:
  application:
    name: CodeCompass
  datasource:
    url: jdbc:postgresql://localhost:5432/code_compass_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: qwer
  jpa: #Config JPA Hibernate DDL
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true
  security: #Config Resource Server Keycloak
    oauth2:
      resource server:
        jwt:
          issuer-uri: http://localhost:8080/realms/aft-mb-api

# Config Server Path and BaseUri for media
media:
  server-path: /home/panha/Pictures/media/
  base-uri: http://localhost:8081/media/

server:
  port: 8081